"""
Graph-Topology-Based Automatic Label Generator for GNN Training.

Labels are derived directly from NetworkX graph structure using heuristics
that reflect the known money mule patterns generated by the simulator:
  - FAN_IN hub:   many senders → one collector
  - FAN_OUT hub:  one distributor → many recipients
  - Multi-hop chain: A → B → C → D (intermediaries)
  - Circular flow: A → B → C → A
  - Rapid forwarding: short dwell times

Labels:
  NORMAL     (0): Isolated, low connectivity, no suspicious topology
  SUSPICIOUS (1): Elevated degree, some suspicious indicators
  MULE       (2): High fan-in+fan-out AND short dwell, OR cycle participant
"""

from typing import Dict, Set, Tuple, Any
import networkx as nx

from .config import (
    LABEL_NORMAL,
    LABEL_SUSPICIOUS,
    LABEL_MULE,
    LABEL_THRESHOLDS,
    LABEL_NAMES,
)


def _detect_cycle_nodes(graph: nx.DiGraph) -> Set[str]:
    """Returns all account nodes that participate in any simple cycle."""
    cycle_nodes: Set[str] = set()
    try:
        for cycle in nx.simple_cycles(graph):
            cycle_nodes.update(cycle)
    except Exception:
        pass
    return cycle_nodes


def _detect_rapid_forward_nodes(graph: nx.DiGraph) -> Set[str]:
    """Returns accounts that have at least one edge with dwell_time < threshold."""
    thresh = LABEL_THRESHOLDS["short_dwell_seconds"]
    rapid_nodes: Set[str] = set()
    for u, v, d in graph.edges(data=True):
        dwell = float(d.get("dwell_time_seconds", -1) or -1)
        if 0 <= dwell <= thresh:
            rapid_nodes.add(u)   # sender is forwarding rapidly
    return rapid_nodes


def _detect_amount_split_nodes(graph: nx.DiGraph) -> Set[str]:
    """Returns accounts that receive a large inflow then split it into smaller outflows."""
    split_nodes: Set[str] = set()
    for node in graph.nodes():
        in_edges  = list(graph.in_edges(node, data=True))
        out_edges = list(graph.out_edges(node, data=True))
        if not in_edges or len(out_edges) < 2:
            continue
        max_in = max((float(d.get("amount", 0) or 0) for _, _, d in in_edges), default=0)
        out_amts = [float(d.get("amount", 0) or 0) for _, _, d in out_edges]
        smaller_outs = [a for a in out_amts if 0 < a < max_in]
        if len(smaller_outs) >= 2:
            split_nodes.add(node)
    return split_nodes


def generate_labels(graph: nx.DiGraph) -> Dict[str, int]:
    """
    Auto-generates NORMAL/SUSPICIOUS/MULE labels for every node in the graph.
    Uses graph topology heuristics derived from known simulator patterns.

    Returns:
        Dict mapping account_id → label_int (0, 1, or 2)
    """
    if graph.number_of_nodes() == 0:
        return {}

    mule_in    = LABEL_THRESHOLDS["mule_min_in_degree"]
    mule_out   = LABEL_THRESHOLDS["mule_min_out_degree"]
    mule_dwell = LABEL_THRESHOLDS["mule_min_short_dwell"]
    susp_in    = LABEL_THRESHOLDS["suspicious_min_in"]
    susp_out   = LABEL_THRESHOLDS["suspicious_min_out"]
    susp_deg   = LABEL_THRESHOLDS["suspicious_min_degree"]
    thresh     = LABEL_THRESHOLDS["short_dwell_seconds"]

    # Pre-compute expensive graph-wide metrics once
    cycle_nodes   = _detect_cycle_nodes(graph)
    rapid_nodes   = _detect_rapid_forward_nodes(graph)
    split_nodes   = _detect_amount_split_nodes(graph)

    labels: Dict[str, int] = {}

    for node in graph.nodes():
        in_deg  = graph.in_degree(node)
        out_deg = graph.out_degree(node)
        tot_deg = in_deg + out_deg

        out_edges = list(graph.out_edges(node, data=True))
        short_dwell_count = sum(
            1 for _, _, d in out_edges
            if 0 <= float(d.get("dwell_time_seconds", -1) or -1) <= thresh
        )

        # ── MULE classification ────────────────────────────────────────────────
        is_mule = False

        # Rule 1: Hub account (fan-in + fan-out + rapid dwell)
        if in_deg >= mule_in and out_deg >= mule_out and short_dwell_count >= mule_dwell:
            is_mule = True

        # Rule 2: Participates in a circular flow (cycle)
        if node in cycle_nodes and tot_deg >= 2:
            is_mule = True

        # Rule 3: High fan-out distributor with amount splitting
        if node in split_nodes and out_deg >= mule_out and in_deg >= 1:
            is_mule = True

        # Rule 4: Rapid-forwarder that also aggregates from multiple senders
        if node in rapid_nodes and in_deg >= mule_in:
            is_mule = True

        if is_mule:
            labels[node] = LABEL_MULE
            continue

        # ── SUSPICIOUS classification ──────────────────────────────────────────
        is_suspicious = False

        # Rule 1: Elevated fan-in OR fan-out
        if in_deg >= susp_in or out_deg >= susp_out:
            is_suspicious = True

        # Rule 2: Rapid forwarding (any short dwell)
        if node in rapid_nodes:
            is_suspicious = True

        # Rule 3: Amount splitting without full mule signature
        if node in split_nodes:
            is_suspicious = True

        # Rule 4: High total degree
        if tot_deg >= susp_deg:
            is_suspicious = True

        if is_suspicious:
            labels[node] = LABEL_SUSPICIOUS
            continue

        # ── NORMAL ─────────────────────────────────────────────────────────────
        labels[node] = LABEL_NORMAL

    return labels


def get_label_distribution(labels: Dict[str, int]) -> Dict[str, int]:
    """Returns count of NORMAL, SUSPICIOUS, MULE labels."""
    dist = {LABEL_NAMES[0]: 0, LABEL_NAMES[1]: 0, LABEL_NAMES[2]: 0}
    for label_int in labels.values():
        name = LABEL_NAMES.get(label_int, "NORMAL")
        dist[name] = dist.get(name, 0) + 1
    return dist


def get_network_pattern(
    graph: nx.DiGraph,
    account_id: str,
    label: int,
) -> str:
    """Returns a human-readable network pattern description for an account."""
    if not graph.has_node(account_id):
        return "ISOLATED_ACCOUNT"

    in_deg  = graph.in_degree(account_id)
    out_deg = graph.out_degree(account_id)

    if label == LABEL_MULE:
        if in_deg >= 3 and out_deg >= 2:
            return "FAN_IN_FAN_OUT_HUB"
        if in_deg >= 3:
            return "FAN_IN_HUB"
        if out_deg >= 3:
            return "FAN_OUT_HUB"

        # Check cycle
        cycle_nodes = _detect_cycle_nodes(graph)
        if account_id in cycle_nodes:
            return "CIRCULAR_FLOW"

        return "MULTI_HOP_CHAIN"

    if label == LABEL_SUSPICIOUS:
        if account_id in _detect_rapid_forward_nodes(graph):
            return "RAPID_FORWARDING"
        if account_id in _detect_amount_split_nodes(graph):
            return "AMOUNT_SPLITTING"
        if in_deg >= 2 or out_deg >= 2:
            return "MULTI_HOP_CHAIN"

    return "ISOLATED_ACCOUNT"
